export const LOGOS = {
  Blog: "blog.svg",
  RxJs: "rxjs.svg",
  Redux: "redux.svg",
  ImmutableJs: "immutablejs.svg",
  JavaScript: "javascript.svg",
  React: "react.svg",
  Parcel: "parcel.png",
  Workbox: "workbox.svg",
  PWA: "pwa.png",
  Angular: "angular.svg",
  WebAssembly: "webassembly.png",
  Vue: "vue.svg",
  Rust: "rust.png",
  NodeJs: "nodejs.png",
  TypeScript: "typescript.svg",
  Deno: "deno.svg",
} as const;
