name: Build and Deploy
on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    name: Deploy Static Site and Docker Container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.1

      # - name: Install Node.js
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: "18.x"

      # - name: Install Project Dependencies
      #   run: npm ci

      # - name: Install Gatsby CLI
      #   run: npm install -g gatsby-cli@5.13.2

      # - name: Build
      #   run: npm run build

      # - name: Copy assets content into public
      #   run: cp -Rf src/assets public

      # - name: Copy index content into public
      #   run: cp src/index.html public

      # - name: Verify build
      #   run: ls -la public

      # - name: Upload artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: site
      #     path: public

      # - name: Install Dependencies 
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y wireguard resolvconf traceroute

      - name: Setup WireGuard Manually
        env:
          WIREGUARD_CONFIG: ${{ secrets.WIREGUARD_CONFIG }}
        run: |
          DEBIAN_FRONTEND=noninteractive sudo apt-get -qq update 
          DEBIAN_FRONTEND=noninteractive sudo apt-get -yqq install wireguard

          echo "$WIREGUARD_CONFIG" > /tmp/wg0.conf

          # Extract necessary information from the config
          PRIVATE_KEY=$(grep PrivateKey /tmp/wg0.conf | cut -d '=' -f 2 | tr -d ' ')
          ADDRESS=$(grep Address /tmp/wg0.conf | cut -d '=' -f 2 | tr -d ' ')
          PEER_PUBKEY=$(grep PublicKey /tmp/wg0.conf | cut -d '=' -f 2 | tr -d ' ')
          PEER_ENDPOINT=$(grep Endpoint /tmp/wg0.conf | cut -d '=' -f 2 | tr -d ' ')
          ALLOWED_IPS=$(grep AllowedIPs /tmp/wg0.conf | cut -d '=' -f 2 | tr -d ' ')

          # Create a temporary file for the private key
          PRIVATE_KEY_FILE=$(mktemp)
          echo "$PRIVATE_KEY" > "$PRIVATE_KEY_FILE"
          chmod 600 "$PRIVATE_KEY_FILE"

          # Set up the WireGuard interface
          sudo ip link add dev wg0 type wireguard
          sudo ip address add dev wg0 $ADDRESS
          sudo wg set wg0 private-key "$PRIVATE_KEY_FILE" peer $PEER_PUBKEY allowed-ips $ALLOWED_IPS endpoint $PEER_ENDPOINT
          sudo ip link set up dev wg0

          # Add routing for allowed IPs
          sudo ip route add $ALLOWED_IPS dev wg0

          # Clean up the temporary private key file
          rm "$PRIVATE_KEY_FILE"

          echo "WireGuard interface status:"
          sudo wg show wg0

          echo "Current network interfaces:"
          ip addr show

          echo "Current routing table:"
          ip route

          echo "WireGuard setup completed manually."
   
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.REGISTRY_HOST }}:30000/contact-form:latest .

      - name: Push Docker image
        run: |
          docker push --insecure-registry ${{ secrets.REGISTRY_HOST }}:30000/contact-form:latest
      
      - name: Cleanup WireGuard
        if: always()
        run: sudo wg-quick down wg0