name: Build and Deploy
on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    name: Deploy Static Site and Docker Container
    runs-on: ubuntu-latest
    environment: production  # Define an environment
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install WireGuard
        run: sudo apt-get update && sudo apt-get install -y wireguard resolvconf
      
      - name: Setup WireGuard
        env:
          WIREGUARD_PRIVATE_KEY: ${{ secrets.WIREGUARD_PRIVATE_KEY }}
          WIREGUARD_ADDRESS: ${{ secrets.WIREGUARD_ADDRESS }}
          WIREGUARD_PUBLIC_KEY: ${{ secrets.WIREGUARD_PUBLIC_KEY }}
          WIREGUARD_ENDPOINT: ${{ secrets.WIREGUARD_ENDPOINT }}
        run: |
          echo "[Interface]
          PrivateKey = $WIREGUARD_PRIVATE_KEY
          Address = $WIREGUARD_ADDRESS

          [Peer]
          PublicKey = $WIREGUARD_PUBLIC_KEY
          AllowedIPs = 0.0.0.0/0
          Endpoint = $WIREGUARD_ENDPOINT" | sudo tee /etc/wireguard/wg0.conf > /dev/null
          
          sudo chmod 600 /etc/wireguard/wg0.conf
          
          echo "WireGuard configuration:"
          sudo cat /etc/wireguard/wg0.conf
          
          echo "Setting up WireGuard interface..."
          sudo ip link add dev wg0 type wireguard
          sudo wg setconf wg0 /etc/wireguard/wg0.conf
          sudo ip address add dev wg0 $WIREGUARD_ADDRESS
          sudo ip link set up dev wg0
          
          echo "WireGuard interface status:"
          sudo wg show

      - name: Test WireGuard Connection
        run: |
          echo "Attempting to ping server..."
          ping -c 4 10.0.0.1 || echo "Ping failed, but continuing..."
          
          echo "Curl test to server..."
          curl -v --connect-timeout 10 http://10.0.0.1 || echo "Curl failed, but continuing..."
          
          echo "Network route:"
          ip route
          
          echo "WireGuard status:"
          sudo wg show

      # - name: Configure Dockerregistry
      #   run: |
      #     echo '{ "insecure-registries" : ["${{ secrets.REGISTRY_HOST }}:${{ secrets.REGISTRY_PORT }}"] }' | sudo tee /etc/docker/daemon.json
      #     sudo systemctl restart docker

      # - name: Build Docker image
      #   run: |
      #     docker build -t 172.104.202.186:30000/contact-form:latest .
      #     #docker build -t ${{ secrets.REGISTRY_HOST }}:${{ secrets.REGISTRY_PORT }}/contact-form:latest .

      # - name: Push Docker image
      #   run: |
      #     docker push 172.104.202.186:30000/contact-form:latest
      #     #docker push ${{ secrets.REGISTRY_HOST }}:${{ secrets.REGISTRY_PORT }}/contact-form:latest
      
      # - name: Cleanup WireGuard
      #   if: always()
      #   run: sudo wg-quick down wg0