name: Build and Deploy
on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    name: Deploy Static Site and Docker Container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.1

      # - name: Install Node.js
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: "18.x"

      # - name: Install Project Dependencies
      #   run: npm ci

      # - name: Install Gatsby CLI
      #   run: npm install -g gatsby-cli@5.13.2

      # - name: Build
      #   run: npm run build

      # - name: Copy assets content into public
      #   run: cp -Rf src/assets public

      # - name: Copy index content into public
      #   run: cp src/index.html public

      # - name: Verify build
      #   run: ls -la public

      # - name: Upload artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: site
      #     path: public

      - name: Install Dependencies 
        run: |
          sudo apt-get update
          sudo apt-get install -y wireguard resolvconf iputils-ping traceroute

      - name: Setup WireGuard Interface
        env:
          WIREGUARD_PRIVATE_KEY: ${{ secrets.WIREGUARD_PRIVATE_KEY }}
          WIREGUARD_ENDPOINT: ${{ secrets.WIREGUARD_ENDPOINT }}
          WIREGUARD_PUBLIC_KEY: ${{ secrets.WIREGUARD_PUBLIC_KEY }}
          WIREGUARD_IPS: ${{ secrets.WIREWARD_IPS }}
          WIREGUARD_ALLOWED_IPS: ${{ secrets.WIREGUARD_ALLOWED_IPS }}
          REGISTRY_HOST: ${{ secrets.REGISTRY_HOST }}
        run: |

          # Check if required variables are set
          if [ -z "$WIREGUARD_PRIVATE_KEY" ]; then echo "WIREGUARD_PRIVATE_KEY is not set"; exit 1; fi
          if [ -z "$WIREGUARD_ENDPOINT" ]; then echo "WIREGUARD_ENDPOINT is not set"; exit 1; fi
          if [ -z "$WIREGUARD_PUBLIC_KEY" ]; then echo "WIREGUARD_PUBLIC_KEY is not set"; exit 1; fi
          if [ -z "$WIREGUARD_IPS" ]; then echo "WIREGUARD_IPS is not set"; exit 1; fi
          if [ -z "$WIREGUARD_ALLOWED_IPS" ]; then echo "WIREGUARD_ALLOWED_IPS is not set"; exit 1; fi
          if [ -z "$REGISTRY_HOST" ]; then echo "REGISTRY_HOST is not set"; exit 1; fi

          echo "$WIREGUARD_PRIVATE_KEY" > privatekey
          sudo chmod 600 privatekey

          sudo ip link add dev wg0 type wireguard
          sudo ip address add dev wg0 $WIREGUARD_IPS

          # Setup WireGuard with the provided configuration
          sudo wg set wg0 \
            private-key privatekey \
            peer $WIREGUARD_PUBLIC_KEY \
            allowed-ips $WIREGUARD_ALLOWED_IPS \
            endpoint $WIREGUARD_ENDPOINT

          sudo ip link set up dev wg0
          sudo ip route add ${{ secrets.REGISTRY_HOST }}/32 dev wg0

          # Display WireGuard configuration for verification
          echo "WireGuard configuration:"
          sudo wg show wg0

          # Display network interfaces
          echo "Network interfaces:"
          ip addr show

          # Display routing table
          echo "Routing table:"
          ip route

      - name: WireGuard Connection Test
        run: |
          echo "Testing connectivity:"
          echo "Pinging WireGuard server endpoint:"
          ping -c 4 $(echo $WIREGUARD_ENDPOINT | cut -d: -f1)
          
          echo "Tracing route to registry:"
          traceroute $REGISTRY_HOST
          
          echo "Attempting to reach registry:"
          curl -v --max-time 10 http://$REGISTRY_HOST:30000/v2/ || echo "Curl failed, but continuing"
          
          echo "WireGuard status:"
          sudo wg show

      - name: Configure Dockerregistry
        run: |
          echo '{ "insecure-registries" : ["${{ secrets.REGISTRY_HOST }}:30000"] }' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker

      - name: Test Registry Connection
        run: |
          echo "Testing connection to registry..."
          curl -v --max-time 10 http://${{ secrets.REGISTRY_HOST }}:30000/v2/ || echo "Curl failed, but continuing workflow"

      - name: Network diagnostics
        run: |
          echo "Pinging registry host..."
          ping -c 4 ${{ secrets.REGISTRY_HOST }}
          echo "Tracing route to registry host..."
          traceroute ${{ secrets.REGISTRY_HOST }}
          echo "Checking registry connection..."
          nc -zv ${{ secrets.REGISTRY_HOST }} 30000

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.REGISTRY_HOST }}:30000/contact-form:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.REGISTRY_HOST }}:30000/contact-form:latest
      
      - name: Cleanup WireGuard
        if: always()
        run: sudo wg-quick down wg0