name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    name: Deploy Static site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.1

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: Install Project Dependencies
        run: npm ci

      - name: Install Gatsby CLI
        run: npm install -g gatsby-cli@5.13.2

      - name: Build
        run: npm run build

      - name: Copy assets content into public
        run: cp -Rf src/assets public

      - name: Copy index content into public
        run: cp src/index.html public

      - name: Verify build
        run: ls -la public

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: public

      - name: Configure Dockerregistry
        run: |
          echo '{ "insecure-registries" : ["${{ secrets.REGISTRY_HOST }}:${{ secrets.REGISTRY_PORT }}"] }' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker

      - name: Build Docker image
        run: |
          docker build -t 172.104.202.186:30000/contact-form:latest .
          #docker build -t ${{ secrets.REGISTRY_HOST }}:${{ secrets.REGISTRY_PORT }}/contact-form:latest .

      - name: Push Docker image
        run: |
          docker push 172.104.202.186:30000/contact-form:latest
          #docker push ${{ secrets.REGISTRY_HOST }}:${{ secrets.REGISTRY_PORT }}/contact-form:latest
      
      - name: Cleanup WireGuard
        if: always()
        run: sudo wg-quick down wg0
