name: Build and Deploy
on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    name: Deploy Static Site and Docker Container
    runs-on: ubuntu-latest
    environment: production  # Define an environment
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install WireGuard
        run: sudo apt install wireguard

      - name: Setup WireGuard
        env:
          WIREGUARD_PRIVATE_KEY: ${{ secrets.WIREGUARD_PRIVATE_KEY }}
          WIREGUARD_ADDRESS: ${{ secrets.WIREGUARD_ADDRESS }}
          WIREGUARD_DNS: ${{ secrets.WIREGUARD_DNS }}
          WIREGUARD_PUBLIC_KEY: ${{ secrets.WIREGUARD_PUBLIC_KEY }}
          WIREGUARD_ENDPOINT: ${{ secrets.WIREGUARD_ENDPOINT }}
        run: |
          echo "[Interface]
          PrivateKey = $WIREGUARD_PRIVATE_KEY
          Address = $WIREGUARD_ADDRESS
          DNS = $WIREGUARD_DNS

          [Peer]
          PublicKey = $WIREGUARD_PUBLIC_KEY
          AllowedIPs = 0.0.0.0/0
          Endpoint = $WIREGUARD_ENDPOINT" | sudo tee /etc/wireguard/wg0.conf > /dev/null
          
          sudo chmod 600 /etc/wireguard/wg0.conf
          sudo wg-quick up wg0

      - name: Test WireGuard Connection
        run: curl -vvv http://10.0.0.1

      # - name: Configure Dockerregistry
      #   run: |
      #     echo '{ "insecure-registries" : ["${{ secrets.REGISTRY_HOST }}:${{ secrets.REGISTRY_PORT }}"] }' | sudo tee /etc/docker/daemon.json
      #     sudo systemctl restart docker

      # - name: Build Docker image
      #   run: |
      #     docker build -t 172.104.202.186:30000/contact-form:latest .
      #     #docker build -t ${{ secrets.REGISTRY_HOST }}:${{ secrets.REGISTRY_PORT }}/contact-form:latest .

      # - name: Push Docker image
      #   run: |
      #     docker push 172.104.202.186:30000/contact-form:latest
      #     #docker push ${{ secrets.REGISTRY_HOST }}:${{ secrets.REGISTRY_PORT }}/contact-form:latest
      
      # - name: Cleanup WireGuard
      #   if: always()
      #   run: sudo wg-quick down wg0